services:
  db:
    image: postgres:15
    container_name: icars_db
    environment:
      POSTGRES_DB: icars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d icars"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - icars_pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: motor-app
    container_name: icars_bot
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/icars
      DB_USER: postgres
      DB_PASS: postgres
